image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - export AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY
  - export AWS_Region

stages:
  - init
  - format
  - plan
  - apply

init:
  stage: init
  script:
    - terraform init \
        -backend-config "bucket=terraform-state-devopsthehardway-test" \
        -backend-config "key=elasticsearch-terraform.tfstate"
      terraform workspace new dev || terraform workspace select dev

format:
  stage: format
  script:
    - cd Terraform-AWS-Services/elasticsearch/elasticsearch_configuration/
    - terraform fmt

plan:
  stage: plan
  script:
    - cd Terraform-AWS-Services/elasticsearch/elasticsearch_configuration/
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - cd Terraform-AWS-Services/elasticsearch/elasticsearch_configuration/
    - terraform apply --auto-approve
  dependencies:
    - plan
  when: manual
